version: "3.8"

services:
  db:
    image: postgres:15
    container_name: event_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_manager
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./backend
    restart: always
    container_name: event_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5433/event_manager?schema=public"
    depends_on:
      - db

  client:
    build: ./frontend
    container_name: event_client
    ports:
      - "5173:5173" # Порт для Vite
    depends_on:
      - api

volumes:
  db_data:
